version: "3"

services:
  multiverse-postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: multiverse
      POSTGRES_USER: multiverse
      POSTGRES_PASSWORD: multiverse
    ports:
      - "127.0.0.1:55432:5432"
    networks:
      - multiverse

  multiverse-phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=multiverse
      - PHP_PG_ADMIN_SERVER_HOST=multiverse-postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=multiverse
      - PHP_PG_ADMIN_SHOW_ADVANCED=true
      - PHP_PG_ADMIN_SHOW_COMMENTS=true
      - PHP_PG_ADMIN_OWNED_ONLY=true
      - PHP_PG_ADMIN_SHOW_SYSTEM=true
      - PHP_PG_ADMIN_SHOW_OIDS=true
    ports:
      - "127.0.0.1:58081:80"
    depends_on:
      - multiverse-postgres
    networks:
      - multiverse

  multiverse-service:
    image: multiverse-service
    environment:
      - RUST_LOG=multiverse_lib=debug,info
      - DATABASE_URL=postgres://multiverse:multiverse@multiverse-postgres/multiverse
    ports:
      - "127.0.0.1:58000:8000"
    depends_on:
      - multiverse-postgres
    networks:
      - multiverse

networks:
  multiverse:
