[package]
name = "multiverse"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[lib]
name = "multiverse_lib"

[[bin]]
name = "multiverse"

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.13"
tracing-futures = "0.2.4"
tracing-log = "0.1.1"
tracing-subscriber = "0.2.5"
log = "0.4.8"
chrono = "0.4.11"
actix-rt = "1.1.1"
serde = { version = "1.0.106", features = ["derive"] }
config = "0.10.1"
actix-web = "2.0.0"
actix-cors = "0.2.0"
actix-http = "1.0.1"
async-trait = "0.1.30"
simple-error = "0.2.1"
futures = "0.3.4"
bb8 = "0.4.2"
bb8-postgres = "0.4.0"
tokio-postgres = "0.5.4"
postgres-types = "0.1.1"
thiserror = "1.0.16"
rust-embed = "5.5.1"
testcontainers = "0.9.1"
lazy_static = "1.4.0"
serde_json = "1.0.52"
bytes = "0.5.4"
insta = "0.16.0"
cucumber_rust = "0.6.7"
jsonpath = "0.1.1"
galvanic-assert = "0.8.7"

[[test]]
name = "cucumber"
harness = false
