version: "3"

services:
  multiverse-dev-postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: multiverse
      POSTGRES_USER: multiverse
      POSTGRES_PASSWORD: multiverse
    ports:
      - "127.0.0.1:45432:5432"
    networks:
      - multiverse-dev

  multiverse-dev-phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=multiverse
      - PHP_PG_ADMIN_SERVER_HOST=multiverse-dev-postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=multiverse
      - PHP_PG_ADMIN_SHOW_ADVANCED=true
      - PHP_PG_ADMIN_SHOW_COMMENTS=true
      - PHP_PG_ADMIN_OWNED_ONLY=true
      - PHP_PG_ADMIN_SHOW_SYSTEM=true
      - PHP_PG_ADMIN_SHOW_OIDS=true
    ports:
      - "127.0.0.1:48081:80"
    depends_on:
      - multiverse-dev-postgres
    networks:
      - multiverse-dev

networks:
  multiverse-dev:
